### ISSUE TITLE
too many compact unwind infos in function anon for architecture i386

### ISSUE THREAD

**Issue by Nandulucky** [rajshahuk/Google-Analytics-Example-iOS#2]
Hi,

I'm using this sample to implementing the Google Analytics sample.
I was imported the Google Analytics 2.0 files in my app, At the time my app is working properly.
But in appDelegate DidFinishLaunchWithOptions method, I write an code of GAI SharedInstance method I got an Issue Below.

"too many compact unwind infos in function anon for architecture i386"
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Please help me.

Thanks,
Nandu K.

**Comment by rajshahuk** [comment]
There is new version of GA that I suggest you look at, the examples on the website are pretty good now: https://developers.google.com/analytics/devguides/collection/ios/v3/?ver=swift#get-config
